apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: team-black-development-app-specs
  namespace: argo-cd
  finalizers: 
    - resources-finalizer.argocd.argoproj.io
spec:
  description: Team Black Development Environment Application Specifications
  sourceRepos:
  - '*'
  destinations:
  - namespace: team-black
    server: https://kubernetes.default.svc
  - namespace: argo-cd
    server: https://kubernetes.default.svc
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
