apiVersion: v1
kind: Pod
metadata:
  name: busybox
spec:
  containers:
  - image: yauritux/busybox-curl:latest
    command:
      - sleep
      - "infinity"
    imagePullPolicy: IfNotPresent
    name: busybox
  restartPolicy: Always
