apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: REPLACE-wildcard-crt
  namespace: ssl-certificates
spec:
  secretName: REPLACE-wildcard-tls-secret
  issuerRef: 
    kind: ClusterIssuer
    name: letsencrypt-prod
  commonName: "*.REPLACE.io"
  dnsNames:
    - "*.REPLACE.io"
